### ISSUE TITLE
Update License files to credit additional SVGs and Fonts

### ISSUE THREAD

**Issue by elfbutt** [elfbutt/koreader-coverbrowserclean#13]
Please copy and update the license with the new image file names into the plugin folder. thanks

https://github.com/elfbutt/koreader-coverbrowserclean/blob/master/resources/icons/mdlight/LICENSE-SIL-OFL-1.1.md
https://github.com/elfbutt/koreader-coverbrowserclean/blob/master/resources/icons/mdlight/license.txt

**Comment by joshuacant** [comment]
Fonts too, if we continue down that path.

**Comment by joshuacant** [comment]
I think we should have a separate license file that's included in the .plugin folder just to cover our additions, so that it's distributed with the zip releases.

**Comment by elfbutt** [comment]
Yes agreed. 

and frankly https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository
