### ISSUE TITLE
File picker is all busted

### ISSUE THREAD

**Issue by elfbutt** [elfbutt/koreader-coverbrowserclean#15]
in my quest to make the normal book list look like like a directory listing i made the actual directory listing less useful

**Comment by elfbutt** [comment]
All kinds of issues in file picker with the change to the footer and list menu

**Comment by elfbutt** [comment]
https://github.com/elfbutt/koreader-coverbrowserclean/commit/e99a31c811622ec20774ab58a4b6390081e5c64b

this fixes the list of items overflowing beyond the footer, and returns the slashes to the end of directory names while in the "pathchooser"

To bring the up arrow back will require edits to how the cover art for directories is made
The "123 books" count should also say "123 files" while in this mode

**Comment by joshuacant** [comment]
> [e99a31c](https://github.com/elfbutt/koreader-coverbrowserclean/commit/e99a31c811622ec20774ab58a4b6390081e5c64b)
> 
> this fixes the list of items overflowing beyond the footer, and returns the slashes to the end of directory names while in the "pathchooser"
> 
> To bring the up arrow back will require edits to how the cover art for directories is made The "123 books" count should also say "123 files" while in this mode

yeah so i did all this. what next boss?

**Comment by elfbutt** [comment]
all issues solved by a brave coder

**Comment by elfbutt** [comment]
The Up Arrow disappears if you navigate to whatever folder you set as Home and you are then trapped in there

**Comment by joshuacant** [comment]
brave coder has done the needful
