### ISSUE TITLE
Name Choice, Documentation

### ISSUE THREAD

**Issue by joshuacant** [elfbutt/koreader-coverbrowserclean#19]
What do we want to do, in terms of assisting anyone else crazy enough to want this? Steps? Limitations? Do we want to let people create issues for bug reports? There's a lot we can't test with just our 2 kobo readers. Expectations should be set.

Would also need a distinct name. What happens when someone enables this and coverreader at the same time lol

**Comment by joshuacant** [comment]
Speaking of the name change... Should we (can we???? we know there are hardcoded checks in koreader for this specific plugin by name) change the class names, settings names, etc so they don't collide with original coverbrowser?

**Comment by elfbutt** [comment]
![FileManager_2024-09-10_225323](https://github.com/user-attachments/assets/ccaa8843-1ab7-42e9-9111-5906c3ff0e8a)
![FileManager_2024-09-10_225417](https://github.com/user-attachments/assets/13391a45-111e-452d-ab5e-373f11b5a170)
![FileManager_2024-09-10_225316](https://github.com/user-attachments/assets/0c8595a9-ffe8-4ada-a42c-69782b77d7e9)

**Comment by elfbutt** [comment]
In case we want them, the same folders in original Cover Browser:

![FileManager_2024-09-10_231843](https://github.com/user-attachments/assets/bc531a2d-0456-4f86-ac2d-9407c89564f7)
![FileManager_2024-09-10_231930](https://github.com/user-attachments/assets/0b139ddd-e4e2-42b3-9a10-a8f91a7517f0)
![FileManager_2024-09-10_231643](https://github.com/user-attachments/assets/4b636162-e225-4aaa-879a-90e2b1de674e)

**Comment by joshuacant** [comment]
Given that this was made _by_ two people _for_ two people we should list the baked-in limitations:

1. English language UI
2. English language eBooks
3. Kobo Devices
4. Use of Calibre and the P(XXX) method
5. ...more goes here...

**Comment by joshuacant** [comment]
A list of changes/what's included would also be good:

1. Design changes to List View
2. Additional title bar buttons
3. Book-sized Progress bar, requires: P(XXX)
4. Design changes to Book Status Page
5. ...more goes here...
