### ISSUE TITLE
Exiting Book to List Bug

### ISSUE THREAD

**Issue by joshuacant** [elfbutt/koreader-coverbrowserclean#21]
Exiting from a book back to the listview doesn't "auto-scoll" to the right page for the book you were viewing. You're left at page "1 of X" of the correct folder instead.

**Comment by joshuacant** [comment]
This bug exists only in the "detailed list" display modes. the others (classic, mosaic) work as expected.

**Comment by elfbutt** [comment]
The fact it's working in mosaic mode is a good sign, mosaic mode is part of the plugin

**Comment by elfbutt** [comment]
https://github.com/elfbutt/koreader-coverbrowserclean/commit/90327602c67ca23716485e060cb0595ee2bf6e6f

This was due to something I was trying when getting the title bar size stuff working. I don't think line was necessary at all and should not have been left in.
