### ISSUE TITLE
Non-List Display Mode Bugs

### ISSUE THREAD

**Issue by joshuacant** [elfbutt/koreader-coverbrowserclean#22]
If you change the display mode to Classic:

A tiny bit of the original subtitle text is visible. Need to suppress display? (to trigger this, change the mode and then change the folder. just changing the mode is not enough)

An extra bottom border line near the footer is drawn (because the last item in the list is drawing its own line, need to suppress like we do in listview?)

Changing the mode to classic, opening a book, then exiting the book, restores the whole UI back to stock, titlebar and footer and everything. Changing back to listview isn't enough to restore the header and footer, but repeating the open/close book is.

Definite conversation to be had here about "do we care? we're already forcing our opinions in other ways." maybe "yeah that's how it is, stick to list view" is the answer?

**Comment by elfbutt** [comment]
I cannot recreate the first item without also going into classic mode

**Comment by elfbutt** [comment]
I get a crash when switching from classic mode to list mode when a book is on the list mode screen. Something about how the directory info (counts of subfolders and files) is being built is actually getting called on books when this change is made

**Comment by elfbutt** [comment]
This stuff nags at me and I want to fix it. I DONT want to overhaul those views. I'm surprised the titlebar and footer work as well as they do in mosaic view, they look nice.

**Comment by joshuacant** [comment]
> I cannot recreate the first item without also going into classic mode

Confirmed. Going from list straight to mosaic is fine. I edited OP to be accurate.

**Comment by elfbutt** [comment]
https://github.com/elfbutt/koreader-coverbrowserclean/commit/df1d2020a8c277e12da385b36a2d0902c8dd9584

When you switch from list or mosaic view to classic view, classic view will now be shown with its original full sized title bar and footer. This solves all issues on the classic view end, I believe. 

I have not yet set this up in the other direction.

**Comment by elfbutt** [comment]
https://github.com/elfbutt/koreader-coverbrowserclean/commit/f4a82784d21f5798620fa3705dc35c86e385298d

everything fixed including the thing with switching into a folder that displays books
