### ISSUE TITLE
Remove/Enforce Settings

### ISSUE THREAD

**Issue by joshuacant** [elfbutt/koreader-coverbrowserclean#23]
We're making a lot of choices about coverbrowser settings that we might not even be aware of. 

We should do a fresh koreader install and a fresh coverbrowser install to see what it looks like with defaults.

We should then remove/constrain/force settings as needed. Priority should be (imo) on preventing the UI from breaking but allow as much choice as possible.

**Comment by joshuacant** [comment]
filing cabinet -> settings -> mosaic settings -> progress -> currently % is always shown, the "show num pages instead of %" toggle should be either renamed to "show num pages" OR the setting should actually switch between the two

**Comment by joshuacant** [comment]
filing cabinet -> settings -> mosaic settings -> progress ->"show num pages left to read" works, but kinda ugly, also uses the "to read" phrase so maybe "New" for unopened books should say "To Read" to match

**Comment by joshuacant** [comment]
filing cabinet -> settings -> mosaic settings -> display hints-> all of these are silly. description does put a little rectangle in there, but the other 2 don't seem to do anything. i vote: get rid of this entire settings block and force them off.

**Comment by joshuacant** [comment]
filing cabinet -> settings -> mosaic settings -> series ->

append to authors: works, looks fine. 
append to title: works, looks stupid. 
separate line: the GOAT option. works and looks good.
no series options selected: works.

**Comment by joshuacant** [comment]
filing cabinet -> settings -> mosaic settings -> show file properties: yeah so this is just skipped entirely if the P(XXX) code activates. should probably fix that.

**Comment by elfbutt** [comment]
> filing cabinet -> settings -> mosaic settings -> progress -> currently % is always shown, the "show num pages instead of %" toggle should be either renamed to "show num pages" OR the setting should actually switch between the two

if we accidentally disabled some settings we probably just need to look for the original flag that controlled them and add it back in to cover our new stuff

**Comment by joshuacant** [comment]
> filing cabinet -> settings -> mosaic settings -> display hints-> all of these are silly. description does put a little rectangle in there, but the other 2 don't seem to do anything. i vote: get rid of this entire settings block and force them off.

Description hint settings menu item is commented out, along with the description hint code in listmenu. covermenu doesn't seem to have any code that references the description hint. description hint code commented out in mosaicmenu.

**Comment by joshuacant** [comment]
All of the settings under the "Progress" sub-menu work as expected.

Still need to do the fresh install test, and maybe other things, so I'm keeping this open to track those things and more!

**Comment by joshuacant** [comment]
New options and default for portrait list items per page set.

%1 bug remains in classic mode item font size.

**Comment by joshuacant** [comment]
I think with the splitting off of that one, we're done here. Wrap it up.
