### ISSUE TITLE
History and Favorites (Collections) mode in List View goes beyond footer

### ISSUE THREAD

**Issue by elfbutt** [elfbutt/koreader-coverbrowserclean#24]
history can be so cruel

**Comment by joshuacant** [comment]
Favorites too. :( :(

**Comment by elfbutt** [comment]
Issue may have been caused from a previous fix no longer needed

https://github.com/elfbutt/koreader-coverbrowserclean/commit/488b4092ad2b888e6f944affd80cb6759cea33b2
